/**
 * This file was automatically generated by Stylus and represents a Rust program.
 * For more information, please see [The Stylus SDK](https://github.com/OffchainLabs/stylus-sdk-rs).
 */

// SPDX-License-Identifier: MIT-OR-APACHE-2.0
pragma solidity ^0.8.23;

interface IPetition {
    function init(string calldata name, string calldata title, string[] memory links) external;

    function getPetitionText() external view returns (string memory);

    function getPetitionTitle() external view returns (string memory);

    function getSourceLinks() external view returns (string[] memory);

    function getSignersCount() external view returns (uint32);

    function sign(uint256 world_id) external;
}
